### ISSUE TITLE
Extended varients do not get generated

### ISSUE THREAD

**Issue by 8176135** [MartinKavik/postcss-typed-css-classes#13]
Great plugin!, however I've been running into an issue where any variants added to extend gets ignored, and only the default variants are generated. 

e.g. active is not generated with this config, hover for example is as it is in the default set
```
module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: { },
  variants: {
    extend: {
      backgroundColor: ['active'],
    }
  },
  plugins: [],
}
```

The following works as expected, active is generated, hover is not, as the defaults gets overridden.
```
module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: { },
  variants: {
    backgroundColor: ['active'],
    extend: { }
  },
  plugins: [],
}
```

It's not a big deal as I can just specify all the variants I want directly, ignoring whatever is in the default set, but still something that should be addressed.

**Comment by MartinKavik** [comment]
The plugin is only a preprocessor => it looks like a problem with tailwind.

I would guess this is a classic problem with Javascript - API is changed but your incompatible code is accepted and possible errors ignored. 
So in this case, it looks like variants API has been changed:
- v1 - https://v1.tailwindcss.com/docs/configuring-variants
- v2 - https://tailwindcss.com/docs/configuring-variants

Notice missing keyword `extend` in the docs for `v1`. So probably you are looking at the new docs but using the old tailwind version - could you verify it, please?
(If so, feel free to update Seed webpack quickstart if you are using it)

**Comment by 8176135** [comment]
Ah, you're right, I was still on the old tailwindcss version. 

However, when I updated to v2, it contains cutoffs like 2xl (e.g. `2xl:duration-300`), which will result in a rust field of `2xl__duration_300`, which would throw a compiler error, since field names can't start with a number.

Also tailwind 2 added the .5 increments to some classes (e.g. `lg:translate-x-2.5`), and that doesn't get changed in the rust fields, resulting in a field of `lg__translate_x_2.5`, which isn't valid either.

**Comment by MartinKavik** [comment]
If you want to resolve it:
1. Add a new file with input test data in [input_data](https://github.com/MartinKavik/postcss-typed-css-classes/tree/master/tests/input_data) folder. E.g. `numbers_input_data.css`
2. Add a new file with the expected output in [rust_generator_test](https://github.com/MartinKavik/postcss-typed-css-classes/tree/master/tests/rust_generator_test). E.g. `rust_generator.numbers.expected_output`
3. Modify [escape function](https://github.com/MartinKavik/postcss-typed-css-classes/blob/master/generators/rust_generator.js#L80-L89) in Rust generator.
4. Make sure the tests have passed. You may need to modify other generators for all tests to pass.

Please close this issue and create a new one with a title like `Invalid Rust identifiers with numbers` with the link to your previous comment if you want to continue the discussion. Thanks!
