### ISSUE TITLE
Tailwind 2.0 support

### ISSUE THREAD

**Issue by gentoid** [MartinKavik/postcss-typed-css-classes#14]
In Tailwind 2.0 it was introduced new default classes, which are generated to incorrect Rust code:
- new extra-wide break point `2xl`, which contains leading number
- decimal sizes, e.g. `0.5` or `1.5`

It'd be good if this project has support for that changes

**Comment by MartinKavik** [comment]
The issue has already been discussed a bit on Discord or somewhere else (I can't find it now). 

It should be relatively simple to fix it:
1. Update the function [escapeClassName](https://github.com/MartinKavik/postcss-typed-css-classes/blob/6810a8a6d4d7e6323dbcdcc6008a019d6d9cb970/generators/rust_generator.js#L80-L89)
2. Add a new file `number_input_data.css` to the folder [tests/input_data](https://github.com/MartinKavik/postcss-typed-css-classes/tree/master/tests/input_data) with CSS that contains classes like `2xl` and `0.5`
3. Add a new file `rust_generator.number.expected_output` to the folder [tests/rust_generator_test](https://github.com/MartinKavik/postcss-typed-css-classes/tree/master/tests/rust_generator_test) with the content corresponding to the `input_data` defined in the previous step
4. Add / modify other files to make all tests successful (`yarn test` should be enough to prove it; run `yarn` to install required dependencies)

However I'm not sure how should the generated names look like - for instance: should `2xl` be renamed to `r#2xl` or to `_2xl` or to something else to make a valid Rust identifier?
Feel free to suggest names and create a PR - I would be very glad.

**Comment by MartinKavik** [comment]
Resolved by PR https://github.com/MartinKavik/postcss-typed-css-classes/pull/15
