### ISSUE TITLE
Tailwind is not fully purged

### ISSUE THREAD

**Issue by aklajnert** [MartinKavik/postcss-typed-css-classes#19]
Since `0.2.1`, `Tailwind` is not purged properly. From my investigation, classes with names like `.space-y-0` are purged, but with `.space-y-0\.5` are not.  
It seems like there's a missing escape in ```let regex = RegExp(`\\b${ class_.name }\\b`)```, but when I've changed it, the `.md\:hover\:bg-blue:hover` declaration from the tests also gets purged, and I'm not sure if that's a good thing.

The difference is huge, see [attached file](https://github.com/MartinKavik/postcss-typed-css-classes/files/6335713/samples.zip) to compare stylesheet purged with 0.2.0 and 0.2.3.

**Comment by MartinKavik** [comment]
Thanks for investigation! Feel free to create a PR with the implementation that makes the most sense to you :)

**Comment by aklajnert** [comment]
@MartinKavik thanks for merging my PR. Can you release the new version soon, or you're waiting for something else?

**Comment by MartinKavik** [comment]
@aklajnert Version `0.2.4` has just been released.
