### ISSUE TITLE
Name clash

### ISSUE THREAD

**Issue by linuxuser586** [MartinKavik/postcss-typed-css-classes#25]
https://github.com/MartinKavik/postcss-typed-css-classes/blob/67ded3482681d6fcca63063ce0cee6dc93e16f1b/generators/rust_generator.js#L80

The function is causing naming clashes and I'm not sure how to solve it without creating a breaking change. For example, material design uses BEM and there is an instance where an identifier can be both an element and a modifier. Please let me know if you have any ideas on how to address this without a breaking change. A breaking change is acceptable if there is no way to make this a non-breaking change.

```css
mdc-button__touch
mdc-button--touch
```

**Comment by MartinKavik** [comment]
Perhaps an additional optional config property (something similar to https://github.com/MartinKavik/postcss-typed-css-classes#options) would help to avoid doing a breaking change. 
Feel free to create a PR.

**Comment by linuxuser586** [comment]
@MartinKavik That is what I came up with. I will create a pull request for you to review and provide any feedback.
